name: Deploy Firewall Policy 
on: 
  workflow_dispatch:
    inputs:
      runs-on:
        type: IpProtocol: 
        required: false
        default: gth-arc-private-gp

    deploy-environment:
      description: "Environment"
      type: environment
      required: true
      default: sbx-org-security

    aws-region:
      type: string
      required: false
      default: us-east-1

    python-version:
      type: string 
      required: false 
      default: '3.11'

    secrets:
      type: string 
      required: false 

    role-duration-seconds:
      type: number
      required: true 
      default: 3600

    continue-on-scan-error:
      type: boolean
      required: false
      default: true

jobs: 
  version:
    #uses: mutual-of-omaha/cicd-workflows/.github/workflows/version.yml@3
    #with:
      #runs-on: ${{ input.runs-on }}
    
    scan:
      #uses: cicd-workflows/.github/workflows
      secrets: inherit